name: stepModify
on:
  schedule:
    - cron : '00 22 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  modify_job:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutCode
      uses: actions/checkout@v4

    - name: SetupPython
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: RunMainUser1
      run: python wxsportWithParam.py ${{ secrets.IPHONE1 }} ${{ secrets.VAL1 }}
    - name: RunMainUser2
      run: python wxsportWithParam.py ${{ secrets.IPHONE2 }} ${{ secrets.VAL2 }}
      env:
        IPHONE_1: ${{ secrets.IPHONE1 }}
        IPHONE_2: ${{ secrets.IPHONE2 }}
        PASSWD_1: ${{ secrets.VAL1 }}
        PASSWD_2: ${{ secrets.VAL2 }}

