name: stepModify
on:
  schedule:
    - cron : '00 22 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutCode
      uses: actions/checkout@v4

    - name: SetupPython
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: RunMain
      run: python wxsport.py
      env:
        IPHONE_1: ${{ secrets.IPHONE1 }}
        IPHONE_2: ${{ secrets.IPHONE2 }}
        PASSWD_1: ${{ secrets.VAL1 }}
        PASSWD_2: ${{ secrets.VAL2 }}

